name: adaptation_modelling_env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - shapely>=2.0
  - geopandas
  - jupyter
  - rasterio
  - xarray
  - pytest
  - black
  - ruff
  - openpyxl
  - pip
  - pip:
    - pyarrow
    - snkit


